### ISSUE TITLE
Profile pics not being loaded after configuring one

### ISSUE THREAD

**Issue by davidmarcelbaum** [Niravpatel129/Quiz-Arena-Frontend-Scaffold#1]
My first attempts were in vein getting the image picker to even select an image. It would crash the app on the second attempt.

https://github.com/Niravpatel129/Quiz-Arena-Frontend-Scaffold/assets/51487830/bbdd1f52-489f-44b6-9e6a-bebbf042f472

After reloading the app from scratch and retrying, I can select an image but it never shows as a profile pic

System is Android 10 on Redmi 9, App version is 3.7.0

**Comment by Niravpatel129** [comment]
Thanks for the bug report, I have a fix in mind and will be deployed in this fix releasing later today.
