### ISSUE TITLE
App crashes at launch on Android

### ISSUE THREAD

**Issue by davidmarcelbaum** [Niravpatel129/Quiz-Arena-Frontend-Scaffold#2]
Version 3.10.0 keeps crashing at launch on my Android (version 10, Xiaomi Redmi 9).

I see the splash screen for half a secind and it crashes. Hundred percent reproducible on my device :-)

**Comment by Niravpatel129** [comment]
Pushing a fix build now.

**Comment by davidmarcelbaum** [comment]
Is the new release out already? I have not received an update through Google Play Store.

**Comment by Niravpatel129** [comment]
Yup, the new release is out, and I confirmed it fixed the crashing issue. Whenever you have a chance, can you check for an update and let me know if it fixed the issue for you? 

Can you also reset your local storage if the update does not fix the issue, there has been structural changes to how the streaks are being handled.

**Comment by davidmarcelbaum** [comment]
Can confirm it works :-)

[SOLVED]
